### ISSUE TITLE
Probably unwanted behavior when cleaning path

### ISSUE THREAD

**Issue by horde3d** [CloudPolis/webdav-client-cpp#48]
What's the intention for the code here:
https://github.com/CloudPolis/webdav-client-cpp/blob/d1bbbf939b39cb7f17acaefe5e0ccce658325faa/sources/client.cpp#L453

If target_path = /test/example/, target_path_without_sep will be equal to target_path. If target_path = /test/example, target_path_without_sep will be /test/. But I guess the intention was:

```
auto target_path_without_sep = target_urn.path();
if( !target_path_without_sep.empty() && target_path_without_sep.back() == '/' )
     target_path_without_sep.resize(target_path_without_sep.length() - 1);
```

**Comment by rusdevops** [comment]
I grant you access to this repository (for create new branches).

**Comment by horde3d** [comment]
Thanks, but I probably won't do much with the library in the future. Just need it for a quick and dirty demo application.
